function [ functionMap ] = createFunctionHandleMap()
%CREATEFUNCTIONHANDLEMAP Put your decriptor here, so then it can be found
%using a name - the function handle will be returned..

names = { 'stackedLab', 'combinedLab', 'statisticsLab',...
          'singularValues','singularValues2','stackedUV','stackedUSV',...
          'compressedDiagonal','UVBasisFFT','WindowFFT'};
functionHandles = ...
   { @LabStackedHistograms, @LabCombinedHistogram, @LabImageStatistics,...
     @SVDDescriptor, @SVDSingularValue, @SVD_UV_Stacked, @SVD_USV_Stacked,...
     @SVDDiagonal, @SVDBasisFFT,@computeBoundedFFT};
 
functionMap = containers.Map ( names, functionHandles );

end

