function [ functionMap ] = createFunctionHandleMap()
%CREATEFUNCTIONHANDLEMAP Put your decriptor here, so then it can be found
%using a name - the function hanlde will be returned to use
names = { 'stackedRGB', 'combinedRGB', 'statisticsRGB',...
          'stackedHSV', 'combinedHSV', 'statisticsHSV',...
          'stackedLab', 'combinedLab', 'statisticsLab'};
functionHandles = ...
   { @stackedHistogramsRGB, @combinedHistogramsRGB, @imageStatisticsRGB,...
     @stackedHistogramsHSV, @combinedHistogramsHSV, @imageStatisticsHSV,...
     @stackedHistogramsLab, @combinedHistogramsLab, @imageStatisticsLab};
 
functionMap = containers.Map ( names, functionHandles );

end

